version: '3.9'
services:
  app:
    container_name: app
    image: demo-project
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - SERVER_PORT=8080
      - POSTGRES_URL=jdbc:postgresql://postgresserver/postgres
    command: ./mvnw spring-boot:run

  postgres:
    container_name: postgresserver
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
    - pg-db-data:/var/lib/postgresql/data/

volumes:
  pg-db-data: