spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  data:
    rest:
      detection-strategy: annotated
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    drop-first: true
    change-log: db/changelog/db.changelog-master.xml
