spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo-project
    username: fjrd

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    drop-first: true
    change-log: db/changelog/db.changelog-master.xml


